### ISSUE TITLE
Your website contains an incorrect statement

### ISSUE THREAD

**Issue by LetsRaceBwoi** [NewSims3/TS3.World#1]
Who said I was reverse engineering? I'm re-creating The Sims 2 like Project Dollhouse and NIOTSO aim to re-create The Sims Online.  Why are you even stalking my thread anyway?

**Comment by ZackCDLVI** [comment]
* Reverse engineering: the reproduction of another manufacturer's product following detailed examination of its construction or composition.
* It's a public forum.

**Comment by ZackCDLVI** [comment]
P.S.
Tell your friends I'm cleaning up Project Dollhouse:
https://github.com/DigitalDollhouse
https://github.com/DigitalDollhouse/DigitalDollhouse
